### ISSUE TITLE
How do I install the MYNT-EYE OKVIS module package with OKVIS ??? I'm already unknow the step and method when I have read the README.

### ISSUE THREAD

**Issue by linhuixiao** [slightech/MYNT-EYE-OKVIS-Sample#1]
excuse me, I'm using OKVIS doing VIO SLAM reasearch, the following README {#mainpage} document I have not understand yet.

####### 1 #######

the install package is MYNT-EYE-OKVIS-Sample, why the README paper use "okvis_mynt_eye_sample","okvis_app_mynteye_sample"??
what's the meaning:"Before you run okvis_mynt_eye_sample in OKVIS", and the following says "Run the okvis_app_mynteye_sample", where the install unzip package named "MYNT-EYE-OKVIS-Sample"  ?????

######## 2 ########

"4 Run the okvis_app_mynteye_sample,
$ ./okvis_app_mynteye_sample path/to/okvis/config/config_mynteye.yaml 1"

I havn't found /okvis_app_mynteye_sample in the download unzip package "MYNT-EYE-OKVIS-Sample".
AND,
I also havn't found path/to/okvis/config/config_mynteye.yaml, I just found /MYNT-EYE-OKVIS-Sample/config/config_mynteye.yaml, where is wrong???

######## 3 ########

How do I install the MYNT-EYE OKVIS module package with OKVIS ??? I'm already unknow the step and method when I have read the README.

Please make a Detail Instruction , thank you.

**Comment by derekhe89** [comment]
I'm sorry for that. We updated the README, you can see the new README.
