### ISSUE TITLE
在运行okvis的sample报错

### ISSUE THREAD

**Issue by 1216621137** [slightech/MYNT-EYE-OKVIS-Sample#10]
failed：IMU measurement fome the past received
以放弃（核心已转储）
ThreadedKFVio.cpp

**Comment by harjeb** [comment]
可以发下详细的错误日志吗

**Comment by 1216621137** [comment]
> 可以发下详细的错误日志吗

W0215 14:12:59.260752  3704 Frontend.cpp:282] - Skipping propagation as only one IMU measurement has been given to frontend. Normal when starting up.
W0215 14:12:59.418714  3703 Frontend.cpp:192] Tracking failure. Number of 3d2d-matches: 0
W0215 14:12:59.485375  3703 Frontend.cpp:192] Tracking failure. Number of 3d2d-matches: 0
W0215 14:12:59.599278  3703 Frontend.cpp:192] Tracking failure. Number of 3d2d-matches: 0
W0215 14:12:59.694340  3703 Frontend.cpp:192] Tracking failure. Number of 3d2d-matches: 0
terminate called after throwing an instance of 'okvis::ThreadedKFVio::Exception'
  what():  [Exception] /home/mao/catkin_vio/src/MYNT-EYE-OKVIS-Sample/okvis/okvis_multisensor_processing/src/ThreadedKFVio.cpp:557: imuConsumerLoop() assert(imuMeasurements_.empty() || imuMeasurements_.back().timeStamp < data.timeStamp) failed: IMU measurement from the past received
已放弃 (核心已转储)

**Comment by 1216621137** [comment]
> failed：IMU measurement fome the past received
> 以放弃（核心已转储）
> ThreadedKFVio.cpp
