### ISSUE TITLE
mynteye/glog_init.h: No such file or directory

### ISSUE THREAD

**Issue by 510443664** [slightech/MYNT-EYE-OKVIS-Sample#6]
When building, came across this problem.
`[ 98%] Building CXX object CMakeFiles/okvis_app_mynteye_sdk2.dir/okvis_apps/src/okvis_app_mynteye.cpp.o
/home/lyh/MYNT-EYE-OKVIS-Sample/okvis_apps/src/okvis_app_mynteye.cpp:68:31: fatal error: mynteye/glog_init.h: No such file or directory
compilation terminated.`

**Comment by joinAero** [comment]
The log header has changed to `logger.h`. Please `git pull` the latest code.

**Comment by 510443664** [comment]
Hello,some new problems occur
`[ 98%] Building CXX object CMakeFiles/okvis_app_mynteye_sdk2.dir/okvis_apps/src/okvis_app_mynteye.cpp.o
In file included from /usr/local/include/mynteye/logger.h:79:0,
                 from /home/lyh/MYNT-EYE-OKVIS-Sample/okvis_apps/src/okvis_app_mynteye.cpp:68:
/usr/local/include/mynteye/miniglog.h:133:11: error: redefinition of ‘const int google::FATAL’
 const int FATAL   = ::FATAL;`

**Comment by Quitino** [comment]
编译的时候出现错误如下：
/MYNT-EYE-ORB-SLAM2/Examples/Stereo/stereo_mynt.cc:28:28: fatal error: mynteye/logger.h: 没有那个文件或目录
怎么解决啊这个？？
